import type { SkillDef } from '../../../src/contracts/core/definitions.js';
import { skillId } from '../../../src/contracts/core/ids.js';
import { asKey } from '../../authoring.js';
import { coreDef } from '../pack-id.js';
export const tacticTexts:Record<string,string>={};
const rows=[["pincer", "夾擊", "lead", "physical", 40, 16, "前排步兵受創，敵方步兵混亂 2 秒。"], ["cavalry", "騎兵衝鋒", "war", "physical", 35, 15, "突擊敵方弓兵，使其潰退 2.5 秒。"], ["longshot", "遠射", "lead", "buff", 28, 13, "6 秒內，我方弓兵專射敵方弓兵。"], ["infighting", "內訌", "int", "debuff", 34, 17, "6 秒內，敵步兵有 30% 機率攻擊同袍，攻速降低。"], ["misreport", "誤報", "pol", "debuff", 32, 17, "6 秒內，敵弓兵有 35% 機率誤射己方步兵。"], ["fire", "火計", "int", "magic", 35, 14, "火攻敵陣並燃燒 4 秒；平地傷害提升 30%。"], ["inspire", "鼓舞", "lead", "buff", 25, 16, "全軍攻擊提升 25%，持續 7 秒。"], ["shield", "固陣", "lead", "buff", 24, 13, "我方步兵受到的傷害減少 25%，持續 5 秒。"], ["reform", "整軍", "pol", "buff", 24, 15, "解除混亂、潰退與誤導，3 秒內免疫。"], ["toarcher", "轉弓", "lead", "buff", 26, 18, "未接敵的後排步兵改編為弓兵，整備 1.5 秒。"], ["toinfantry", "換盾", "lead", "buff", 22, 15, "前排弓兵改編為步兵，整備 1.5 秒。"], ["pursue", "乘隙追擊", "war", "physical", 30, 14, "攻擊前陣，敵方只剩單一兵種時傷害提升 30%。"], ["mounted", "騎射", "war", "physical", 32, 14, "三輪箭擊，逐輪重新選定敵軍。"], ["volley", "齊射", "war", "physical", 36, 16, "向敵方密集區域射出箭雨，逐箭判定命中。"], ["water", "水攻", "int", "magic", 40, 18, "水勢貫穿敵陣；水域傷害提升 30%。"], ["rocks", "落石", "int", "magic", 38, 17, "落石砸向密集敵軍；山地傷害提升 30%。"], ["taunt", "怒罵", "pol", "debuff", 24, 18, "敵軍攻擊提升 20%、命中減半，持續 6 秒。"], ["ambush", "埋伏", "int", "buff", 42, 24, "敵步兵後方出現最多 100 名伏兵，本關結束離場。"], ["reinforce", "援軍", "pol", "buff", 40, 24, "後方增援最多 100 名弓兵，本關結束離場。"], ["divide", "離間", "pol", "debuff", 45, 22, "招降最多 50 名敵弓兵，暫編我方步兵；不計擊殺。"], ["turncoat", "策反", "int", "debuff", 45, 22, "招降最多 50 名敵步兵，暫編我方步兵；不計擊殺。"], ["lure", "調虎離山", "int", "debuff", 46, 26, "敵方步兵離場 10 秒；仍計入敵軍兵力。"], ["sweep", "橫掃千軍", "war", "physical", 30, 13, "橫掃敵方前排。"], ["crossbow", "連弩急襲", "war", "physical", 28, 12, "六發連弩，目標倒下後接續攻擊鄰近敵軍。"], ["thunder", "轟雷投石", "int", "magic", 44, 20, "三輪投石散落敵陣，不受地形加成。"]] as const;
export const tacticalSkills:readonly SkillDef[]=rows.map(([slug,name,attr,kind,cost,cd,desc],i)=>{
 const prefix='skill.tactic-'+slug;tacticTexts[prefix+'.name']=name;tacticTexts[prefix+'.desc']=desc;
 return coreDef('skill','skill:tactic-'+slug,{skillId:skillId('skill:tactic-'+slug),tier:i>=17?'peerless':i>=6?'fine':'common',nameKey:asKey(prefix+'.name'),descKey:asKey(prefix+'.desc'),cost:Object.fromEntries([attr,...(['lead','war','int','pol'] as const).filter(a=>a!==attr)].slice(0,i>=17?3:i>=6?2:1).map((a,j)=>[a,[380,280,210][j]!])),battleMechanic:slug,supplyCost:cost,cooldownSeconds:cd,action:{kind,actorAttr:attr,ratio:kind==='physical'||kind==='magic'?.22:.25,duration:2}});
});
