import {DEBATE_CARDS,DEBATE_TRAITS,DEBATE_RECOVER,debateBlock,debateIntent,type Debater,type DebateCard} from '../app/card-debate-model.js';
import type {Contest} from '../contracts/core/confrontation.js';
import type {DebateResource} from '../contracts/core/card-debate.js';
import {DuelArt} from './DuelArt.js';
import {DebateIcon,ResourceIcon,ResourceValue,cardEffects,type Effect} from './DebateVisuals.js';
import './duel-hud.css';
import './card-debate.css';
function Vitals({f,name,enemy=false}:{f:Debater;name:string;enemy?:boolean}):React.ReactElement {
 return <section className={`du-vital db-vital ${enemy?'du-enemy':'du-ally'}`} aria-label={`${enemy?'敵方':'我方'}舌戰狀態`}><DuelArt file="status-scroll-v1" className="du-parchment"/><div className="du-vital-inner"><h2>{name}<small title={DEBATE_TRAITS[f.build.trait].description}>{DEBATE_TRAITS[f.build.trait].name}</small></h2>{(['heart','mind'] as const).map(k=><div className={`db-meter db-${k}`} key={k}><ResourceIcon kind={k}/><div role="progressbar" aria-label={`${enemy?'敵方':'我方'}${k==='heart'?'心防':'心力'}`} aria-valuenow={f[k]} aria-valuemin={0} aria-valuemax={k==='heart'?f.maxHeart:f.maxMind}><i style={{width:`${f[k]/(k==='heart'?f.maxHeart:f.maxMind)*100}%`}}/></div><strong>{f[k]}<small>/{k==='heart'?f.maxHeart:f.maxMind}</small></strong></div>)}<div className="db-stock"><ResourceValue kind="evidence" value={`${f.evidence}/5`}/><ResourceValue kind="momentum" value={`${f.momentum}/4`}/><span title={`智力 ${f.build.int}`}>智 {f.build.int}<i className="db-card-back">{f.hand.length}</i></span></div></div></section>;
}
const intentions:Record<string,DebateCard[]>={'攻勢':['proof','pressure','question'],'周旋':['rebut','borrow'],'蓄勢':['claim','focus']};
function ChangeRow({side,effects,card}:{side:'enemy'|'self';effects:Effect[];card?:DebateCard}):React.ReactElement {
 return <section className={`db-change db-${side}`} aria-label={side==='enemy'?'敵方變化':'我方變化'}><header><b>{side==='enemy'?'敵方變化':'我方變化'}</b>{card&&<span title={DEBATE_CARDS[card].name}><DebateIcon card={card}/>{DEBATE_CARDS[card].name}</span>}</header><div>{effects.length?effects.map((e,i)=><ResourceValue key={i} kind={e.kind} value={e.value}/>):<span className="db-no-change">—</span>}</div></section>;
}
export function CardDebateHud({c,paused,selected,onSelect,onPlay,onRules}:{c:Contest;paused:boolean;selected:number|null;onSelect:(i:number|null)=>void;onPlay:(i:number)=>void;onRules:()=>void}):React.ReactElement {
 const d=c.cards!,active=c.phase==='read'||c.phase==='clash',reading=c.phase==='read',f=d.ally,last=d.last,hand=!reading&&last?last.allyHand:f.hand;
 const chosen=selected===null?null:selected===DEBATE_RECOVER?'focus':f.hand[selected]??null;
 const preview=reading&&chosen?cardEffects(chosen,f,d.enemy,selected===DEBATE_RECOVER):null;
 const block=chosen&&selected!==DEBATE_RECOVER?debateBlock(f,chosen):'';
 const changes=(side:'ally'|'enemy'):Effect[]=>last?(['heart','mind','evidence','momentum'] as DebateResource[]).filter(k=>last[side==='ally'?'allyChange':'enemyChange'][k]!==0).map(kind=>({kind,value:(last[side==='ally'?'allyChange':'enemyChange'][kind]>0?'+':'−')+Math.abs(last[side==='ally'?'allyChange':'enemyChange'][kind])})):[];
 return <><Vitals f={f} name={c.allyName}/><Vitals f={d.enemy} name={c.enemyName} enemy/>{active&&<><div className="db-round"><b>{c.round}</b> 合<small>{reading?`${Math.max(0,Math.ceil(25-c.phaseTime))} 秒`:'揭牌'}</small><button onClick={onRules} aria-label="查看舌戰規則">?</button></div>
 <div className="db-intent"><small>{reading?'敵方可能出牌':'雙方揭牌'}</small><div>{(reading?intentions[debateIntent(d)]??[]:last?[last.ally,last.enemy]:[]).map((card,i)=><span key={i}>{i>0&&<em>{reading?'或':'／'}</em>}<DebateIcon card={card}/><b>{DEBATE_CARDS[card].name}</b></span>)}</div></div>
 <section className="db-hand-area" aria-label="舌戰手牌"><header><b>{reading?'選一張牌':'已出牌'}</b><span>智 {f.build.int} · {hand.length} 張</span><button disabled={!reading||paused} className={selected===DEBATE_RECOVER?'db-selected':''} onClick={()=>onSelect(DEBATE_RECOVER)} aria-label="R 整思換牌"><DebateIcon card="focus"/>整思換牌 <kbd>R</kbd></button></header><div className="db-hand" style={{gridTemplateColumns:`repeat(${hand.length},minmax(0,1fr))`}}>{hand.map((card,i)=>{const locked=debateBlock(f,card),played=!reading&&c.choice===i;return <button key={i} className={`db-card ${reading&&selected===i||played?'db-selected':''}`} disabled={!reading||paused} onClick={()=>onSelect(i)} aria-label={`第 ${i+1} 張 ${DEBATE_CARDS[card].name}${reading&&locked?'，'+locked:''}`} aria-pressed={reading&&selected===i} data-locked={!!locked}><kbd>{i+1}</kbd><span className="db-cost"><ResourceIcon kind="mind"/>{DEBATE_CARDS[card].cost}</span><DebateIcon card={card}/><h3>{DEBATE_CARDS[card].name}</h3>{reading&&locked&&<small className="db-lock">{locked}</small>}{played&&<span className="db-seal">已出</span>}</button>;})}</div></section>
 <aside className="db-detail" aria-label="出牌與結算"><header><strong>{preview?DEBATE_CARDS[chosen!].name:last?reading?'上一合結果':'本合結果':'選牌後看效果'}</strong>{preview&&last&&<button onClick={()=>onSelect(null)}>上一合</button>}</header>{preview?<><ChangeRow side="enemy" effects={preview.enemy}/><ChangeRow side="self" effects={preview.self}/><p className="db-detail-note">{preview.note}</p><button className="db-play" disabled={paused||!!block} onClick={()=>selected!==null&&onPlay(selected)}>{block||'出牌'}{!block&&<kbd>Enter</kbd>}</button></>:last?<><ChangeRow side="enemy" effects={changes('enemy')} card={last.enemy}/><ChangeRow side="self" effects={changes('ally')} card={last.ally}/><p className="db-detail-note">{last.notes.join(' · ')||'雙方結算完成'}<small>實際淨變化，含每合心力恢復</small></p></>:<div className="db-empty"><ResourceIcon kind="heart"/><b>擊破對手心防</b><span>選牌 → 看變化 → 出牌</span></div>}</aside>
 </>}</>;
}
