import {duelPresentation} from '../app/duel-presentation.js';
import {DuelReveal} from './DuelReveal.js';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ACTION_NAME,DUEL_ACTIONS,DUEL_TRAITS,DUEL_RULES,actionBlock,attackPower,defensePower,duelHealth,evolutionChance,counters,forecastDuel,duelReadHint,type DuelForecast,type DuelFighter,type DuelAction} from '../app/duel-model.js';
import {type Contest} from '../app/confrontation-demo.js';
import {DuelArt,actionCell} from './DuelArt.js';
import {DuelPortrait} from './DuelPortrait.js';
import './duel-hud.css';
import {duelMatchup} from './duel-matchup.js';
import {Spotlight,spotlightTarget} from './Spotlight.js';
type Resource='stamina'|'health'|'combo'|'faint';
export function DuelResource({kind}:{kind:Resource}):React.ReactElement {return kind==='health'?<span className="dx-resource dx-health-icon" aria-hidden="true"/>:<DuelArt file="status-icons-v1" cell={{stamina:0,combo:2,faint:3}[kind]} className="dx-resource"/>;}
function Gesture({action}:{action:DuelAction|null}):React.ReactElement {return action?<DuelArt cell={actionCell(action)} className="dx-gesture"/>:<DuelResource kind="faint"/>;}
const prey:Record<DuelAction,DuelAction>={attack:'rest',defend:'attack',rest:'defend'};
export function DuelVitals({fighter,enemy=false,name,actorId,forecast}:{fighter:DuelFighter;enemy?:boolean;name:string;actorId:string;forecast?:DuelForecast['ally']|undefined}):React.ReactElement {
 const f=fighter,side=enemy?'敵方':'我方',health=duelHealth(f);
 return <section {...spotlightTarget(!!forecast)} className={`dx-fighter ${enemy?'dx-fighter-enemy':'dx-fighter-ally'}`} aria-label={`${side}單挑數值`}>
  <div className="dx-face-medallion" role="img" aria-label={name}><div className="dx-face-image" aria-hidden="true"><DuelPortrait id={actorId} name={name}/></div><span>{enemy?'敵':'我'}</span></div>
  <div className="dx-fighter-bars"><h2>{name}<span className="dx-combat-ratings"><span className="dx-rating-attack" aria-label={`${side}攻擊力 ${Math.round(attackPower(f))}`} title="目前攻擊力，包含連勢與特性"><DuelArt cell={actionCell('attack')} className="dx-rating-icon"/><b>{Math.round(attackPower(f))}</b></span><span className="dx-rating-defense" aria-label={`${side}防禦力 ${Math.round(defensePower(f))}`} title="目前防禦力，包含連勢"><DuelArt cell={actionCell('defend')} className="dx-rating-icon"/><b>{Math.round(defensePower(f))}</b></span></span></h2>
   {(['health','stamina'] as const).map(key=>{const value=key==='health'?health:f.stamina,max=key==='health'?f.injuryLimit:f.maxStamina,label=key==='health'?'血量':'體力',range=forecast?.[key],delta=range?.[0]??0,extent=range?Math.max(Math.abs(range[0]),Math.abs(range[1])):0,hidden=delta<0&&value>0?Math.min(value,extent)/value*100:0;return <div className={`dx-fight-meter dx-fight-${key}`} key={key}><div role="progressbar" aria-label={`${side}${label}`} aria-valuenow={value} aria-valuemin={0} aria-valuemax={max}><i style={{width:`${value/max*100}%`,clipPath:`inset(0 ${enemy?0:hidden}% 0 ${enemy?hidden:0}%)`}}/>{range&&extent>0&&<em className={`dw-bar-forecast ${delta<0?'dw-loss':'dw-gain'}`} style={{[enemy?'right':'left']:`${(delta<0?value-extent:value)/max*100}%`,width:`${extent/max*100}%`}}/>}</div></div>;})}
   <div className="dx-fighter-status">{f.fainted?<b>昏厥</b>:f.taunted?<b>本合禁防</b>:null}{f.build.trait!=='none'&&<span title={DUEL_TRAITS[f.build.trait].description}>{DUEL_TRAITS[f.build.trait].name}</span>}</div>
  </div>
  {f.progression!==false&&<div className={`dx-fight-combo ${f.combo?'dx-combo-active':''}`} aria-label={`${side} Combo ${f.combo}`} title={`攻擊 +${f.combo*4}% · 防禦 +${f.combo*3}%`}><strong>{f.combo}</strong><span><b>C</b>ombo</span></div>}
 </section>;
}
export function DuelInterface({contest:c,paused,onAnswer,onHelpChange}:{contest:Contest;paused:boolean;onAnswer:(n:number)=>void;onHelpChange:(open:boolean)=>void}):React.ReactElement {
 const [preview,setPreview]=useState<DuelForecast|null>(null),reading=c.phase==='read',presentation=duelPresentation(c),display=c.duelBefore&&c.phase==='clash'&&(presentation.stage!=='combat'||presentation.time<.75)?c.duelBefore:c.duel!;
 return <><DuelVitals fighter={display.ally} name={c.allyName} actorId={c.allyId} forecast={reading?preview?.ally:undefined}/><DuelVitals fighter={display.enemy} name={c.enemyName} actorId={c.enemyId} enemy forecast={reading?preview?.enemy:undefined}/>{['read','clash'].includes(c.phase)&&<DuelControls key={`${c.round}-${c.phase}`} contest={c} paused={paused} onAnswer={onAnswer} onHelpChange={onHelpChange} onPreview={setPreview}/>}<DuelReveal contest={c}/><Spotlight active={reading&&!paused}/></>;
}
export function DuelControls({contest:c,paused,onAnswer,onHelpChange,onPreview}:{contest:Contest;paused:boolean;onAnswer:(n:number)=>void;onHelpChange:(open:boolean)=>void;onPreview:(p:DuelForecast|null)=>void}):React.ReactElement {
 const d=c.duel!,f=d.ally,reading=c.phase==='read';
 const [selected,setSelected]=useState<DuelAction|null>(null),[hovered,setHovered]=useState<DuelAction|null|undefined>(undefined),[back,setBack]=useState(0),[help,setHelp]=useState(false),closeButton=useRef<HTMLButtonElement>(null);
 const hint=duelReadHint(d),history=d.history,end=Math.max(4,history.length-back*4),start=Math.max(0,end-4),rows=history.slice(start,end);
 const changeHelp=(open:boolean)=>{setHelp(open);onHelpChange(open);onPreview(null);};
 const select=(a:DuelAction)=>{if(paused||!reading||actionBlock(f,a))return;setSelected(a);setHovered(undefined);onPreview(null);};
 const confirm=()=>{if(selected&&!paused&&reading&&!actionBlock(f,selected)){onPreview(null);onAnswer(DUEL_ACTIONS.indexOf(selected));}};
 const preview=(enemy:DuelAction|null)=>{if(!selected||paused)return;setHovered(enemy);onPreview(forecastDuel(d,selected,enemy));};
 const clearPreview=()=>{setHovered(undefined);onPreview(null);};
 useEffect(()=>{onPreview(null);return()=>onPreview(null);},[]);
 useEffect(()=>{if(paused){setHovered(undefined);onPreview(null);}},[paused]);
 useEffect(()=>{const open=(e:KeyboardEvent)=>{if(help||e.repeat||e.ctrlKey||e.altKey||e.metaKey||e.key.toLowerCase()!=='h'||e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;e.preventDefault();e.stopImmediatePropagation();changeHelp(true);};window.addEventListener('keydown',open,true);return()=>window.removeEventListener('keydown',open,true);},[help]);
 useEffect(()=>{if(!help)return;closeButton.current?.focus();const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();changeHelp(false);}else if(e.key==='Tab'){e.preventDefault();e.stopImmediatePropagation();closeButton.current?.focus();}else{e.stopImmediatePropagation();}};const context=(e:MouseEvent)=>{e.preventDefault();e.stopImmediatePropagation();changeHelp(false);};window.addEventListener('keydown',close,true);window.addEventListener('contextmenu',context,true);return()=>{window.removeEventListener('keydown',close,true);window.removeEventListener('contextmenu',context,true);};},[help]);
 useEffect(()=>{if(!reading||paused||help)return;const key=(e:KeyboardEvent)=>{if(e.ctrlKey||e.altKey||e.metaKey||e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(['1','2','3'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)select(DUEL_ACTIONS[Number(e.key)-1]!);}else if(e.key==='Enter'&&selected){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)confirm();}else if(e.key==='Escape'&&selected){e.preventDefault();e.stopImmediatePropagation();setSelected(null);clearPreview();}};const context=(e:MouseEvent)=>{if(!selected)return;e.preventDefault();e.stopImmediatePropagation();setSelected(null);clearPreview();};window.addEventListener('keydown',key,true);window.addEventListener('contextmenu',context,true);return()=>{window.removeEventListener('keydown',key,true);window.removeEventListener('contextmenu',context,true);};},[selected,paused,reading,help]);
 const enemies:(DuelAction|null)[]=d.enemy.fainted?[null]:[...DUEL_ACTIONS];
 return <>
 {reading?<section {...spotlightTarget()} className="dw-command" aria-label="單挑指令盤">
 <div className="dw-wheel"><DuelArt file="wheel-platter-v1" className="dw-wheel-platter"/><div className="dw-counter-lines" role="img" aria-label="攻擊剋休養，休養剋防守，防守剋攻擊">{(['attack','rest','defend'] as const).map((action,index)=><div key={action} className={selected===action?'dw-counter-arrow dw-line-lit':'dw-counter-arrow'} style={{transform:`rotate(${index*120}deg)`}}><DuelArt file="wheel-counter-arrow-v1" className="dw-counter-art"/></div>)}</div>
 {DUEL_ACTIONS.map(a=>{const blocked=actionBlock(f,a),points=f.points[a],full=points>=DUEL_RULES.pointsCap;return <button key={a} className={`dw-node dw-node-${a} ${selected===a?'dw-node-selected':''} ${full?'dw-node-full':''}`} style={{'--dw-power':points/DUEL_RULES.pointsCap,'--dw-breath':`${2.8-points/DUEL_RULES.pointsCap*1.3}s`} as CSSProperties} disabled={paused||!!blocked} aria-label={`選擇${ACTION_NAME[a]}${blocked?'，'+blocked:''}`} aria-pressed={selected===a} title={`${ACTION_NAME[a]}動作點 ${points}/${DUEL_RULES.pointsCap} · 升變 ${Math.round(evolutionChance(f,a)*100)}%`} onClick={()=>select(a)}><i className="dw-aura"/><DuelArt cell={actionCell(a)} className="dw-node-art"/>{hint===a&&<span className="dw-enemy-tell" role="img" aria-label={`${c.enemyName}可能使用${ACTION_NAME[a]}`}><DuelPortrait context="duelHint" id={c.enemyId} name={c.enemyName}/></span>}</button>;})}
 <div className="dw-wheel-center"><button className="dw-confirm" disabled={!selected||paused} onClick={confirm}><DuelArt file="wheel-confirm-button-v1" className="dw-confirm-art"/><span>出招</span></button></div></div>
 {selected&&<aside className="dw-possibilities" aria-label="敵方出招推演"><div className="dw-opponent-choices">{enemies.map(enemy=>{const blocked=enemy?actionBlock(d.enemy,enemy):'',current=hovered===enemy,copy=duelMatchup(selected,enemy),relationLabel=enemy===null?'對手昏厥':({win:'剋制',draw:'平手',lose:'被剋制'}[copy.relation]);return <button key={enemy??'faint'} disabled={paused||!!blocked} className={`dw-possibility dw-matchup-${copy.relation} ${current?'dw-possibility-active':''}`} aria-label={`推演敵方${enemy?ACTION_NAME[enemy]:'昏厥'}${blocked?'，'+blocked:''}`} onMouseEnter={()=>preview(enemy)} onMouseLeave={clearPreview} onFocus={()=>preview(enemy)} onBlur={clearPreview} onClick={()=>preview(enemy)}>
 <span className="dw-relation" role="img" aria-label={relationLabel} title={relationLabel}>{enemy===null?<DuelResource kind="faint"/>:<DuelArt file="matchup-icons-v1" cell={{win:0,draw:1,lose:2}[copy.relation]} className="dw-relation-art"/>}</span>
 <span className="dw-possibility-art" role="img" aria-label={enemy?ACTION_NAME[enemy]:'昏厥'}><Gesture action={enemy}/>{hint&&hint===enemy&&<span className="dw-enemy-tell" role="img" aria-label="看破動向"><DuelPortrait context="duelHint" id={c.enemyId} name={c.enemyName}/></span>}</span>
 <span className="dw-result-copy"><strong>{copy.result.title}</strong><span>{blocked||copy.result.effect}</span></span>
 {!blocked&&copy.evolution&&<span className="dw-evolution-copy" aria-label={copy.evolutionSide==='enemy'?'敵方克制時可能升變':'我方克制時可能升變'}><span className="dw-evolution-title"><DuelArt file="matchup-icons-v1" cell={3} className="dw-evolution-icon"/><strong>{copy.evolution.title}</strong></span><small>{copy.evolutionSide==='enemy'?'敵方':'我方'}機率升變</small><span>{copy.evolution.effect}</span></span>}
 </button>;})}</div></aside>}
 </section>:null}
 {help&&<div className="dx-guide-layer"><section className="dx-guide" role="dialog" aria-modal="true" aria-label="單挑規則"><button ref={closeButton} aria-label="關閉規則" onClick={()=>changeHelp(false)}>×</button><h2>攻・防・休</h2><div className="dx-guide-matchups">{DUEL_ACTIONS.map(a=><article key={a}><div><Gesture action={a}/><b>剋</b><Gesture action={prey[a]}/></div><h3>{ACTION_NAME[a]} → {ACTION_NAME[prey[a]]}</h3><p>{a==='attack'?'對手恢復減半，完整傷害':a==='defend'?'承傷 20%，對手耗體 ×2':'恢復體力，對手下合禁防'}</p><small>{a==='attack'?'攻其不備：傷害再 +20%':a==='defend'?'借力打力：免耗體，全傷反彈':'蓄勢待發：恢復 ×1.5'}</small></article>)}</div><div className="dx-guide-basics"><span><DuelResource kind="combo"/><b>連勢</b> 未被剋 +1，克制 +2，受剋歸零</span><span><DuelResource kind="stamina"/><b>昏厥</b> 體力低於 5，下合停動、回體 24</span></div><p>我方連用同招且未被剋，累積動作點、提高升變機率。敵方沒有 Combo、動作點或升變；只有我方克制時可能升變。<br/>雙攻只結算傷害差額；同防後雙方下合禁防。休養回體 48，被攻擊仍回體 24；調息特性另有加成。休養不回復血量。</p><footer>1 / 2 / 3 選招 · Enter 確認 · 出招不限時 · 最多 24 合，比剩餘血量比例。<br/>武力高出 20 起有機會看破，差距越大機率越高。同合提示固定。<br/>光暈越強，動作點越高；滿點呈強光。升變僅在克制時發動。</footer> <section className="dx-history" aria-label="猜拳歷史"><header><b>最近出招</b><span><button aria-label="較早出招紀錄" disabled={history.length<=(back+1)*4} onClick={()=>setBack(back+1)}>‹</button><small>{history.length?`${start+1}–${Math.min(end,history.length)}`:'—'}</small><button aria-label="較新出招紀錄" disabled={!back} onClick={()=>setBack(back-1)}>›</button></span></header><div className="dx-history-grid"><div className="dx-history-label"><small>合</small><b>敵</b><b>我</b></div>{rows.map((r,i)=><div key={start+i} className="dx-history-turn" aria-label={`第 ${start+i+1} 合，敵方${r.enemy?ACTION_NAME[r.enemy]:'昏厥'}，我方${r.ally?ACTION_NAME[r.ally]:'昏厥'}`}><small>{start+i+1}</small>{(['enemy','ally'] as const).map(side=><span key={side} className={counters(r[side],r[side==='ally'?'enemy':'ally'])?'dx-winner':''}><Gesture action={r[side]}/>{counters(r[side],r[side==='ally'?'enemy':'ally'])&&<em>剋</em>}</span>)}</div>)}</div><small>亮框「剋」＝克制對方</small></section></section></div>}
 </>;
}
