import { useEffect,useRef } from 'react';
import type { Session } from '../app/session.js';
import { defs,stageOf,t } from '../app/bootstrap.js';
import { CharacterArt } from './CharacterArt.js';
import { ArtControl } from './ArtControl.js';
import { UiSymbol } from './UiSymbol.js';
export function NotableDetail({s,id,onClose,onLearn}:{s:Session;id:string;onClose:()=>void;onLearn:()=>void}):React.ReactElement{
 const ref=useRef<HTMLButtonElement>(null),member=s.current.roster.members.find(x=>String(x.notableId)===id),def=defs.reader('notable').get(id),name=t(def.nameKey),stage=member?stageOf(member.notableId,s.ctx):'stranger',affinity=member?.affinity??0;
 useEffect(()=>{const previous=document.activeElement;ref.current?.focus();return()=>{if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();};},[]);
 return <div className="game-modal notable-detail-modal" role="dialog" aria-modal="true" aria-label={name+'詳情'} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key==='Tab'){const buttons=e.currentTarget.querySelectorAll<HTMLButtonElement>('button'),first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><section className="notable-detail-paper"><ArtControl ref={ref} kind="close" label="關閉名士詳情" className="panel-close" onClick={onClose}/><div className="notable-detail-portrait"><CharacterArt name={name}/></div><div className="notable-detail-info"><h1>{name}</h1><span className="notable-role">{member?.origin==='superior'?'上司':'同行'}</span><div className="notable-affinity" title={t('stage.'+stage)}><UiSymbol name={stage==='stranger'||stage==='acquainted'?'red':stage==='friendly'?'gold':'green'}/><div role="meter" aria-label={name+'好感'} aria-valuemin={0} aria-valuemax={100} aria-valuenow={affinity} className="notable-affinity-track"><i style={{width:Math.max(0,Math.min(100,affinity))+'%'}}/></div></div><div className="notable-specialty" title={'專長：'+t('attr.'+def.base.specialty+'.short')} aria-label={'專長：'+t('attr.'+def.base.specialty+'.short')}><span className={'entry-stat-icon entry-stat-'+def.base.specialty}/><b>{t('attr.'+def.base.specialty+'.short')}</b></div><ArtControl kind="book" label="查看修習" className="notable-learn" onClick={onLearn}/></div></section></div>;
}
