import { RealmBack } from './RealmBack.js';
import { RealmIcon } from './RealmArt.js';
import { useState } from 'react';
import type { MetaState } from '../contracts/core/state.js';
import { catalog,defs,purchase,t } from '../app/bootstrap.js';
interface Props {readonly meta:MetaState;readonly onMeta:(m:MetaState)=>void;readonly onBack:()=>void}
const paths=[['career','官途','印'],['aptitude','資質','玉'],['talent','天賦','星'],['bond','緣分','結'],['glow','光階','光']] as const;
export function ScreenShop({meta,onMeta,onBack}:Props):React.ReactElement{
 const [category,setCategory]=useState<string>('career');
 const [notice,setNotice]=useState('');
 const [page,setPage]=useState(0);
 const entries=catalog(meta,defs).filter(e=>e.item.category===category);
 return <section className="realm realm-fate"><header className="realm-heading"><div><RealmIcon name="glow"/><h1>天命閣</h1></div><span className="fate-balance"><RealmIcon name="currency"/> {meta.points}</span><RealmBack onClick={onBack}/></header><div className="fate-layout"><nav className="fate-paths" aria-label="成長類別">{paths.map(([key,name])=><button aria-pressed={category===key} className={category===key?'selected':''} key={key} onClick={()=>{setCategory(key);setPage(0);setNotice('');}}><RealmIcon name={key}/>{name}</button>)}</nav><div className="fate-offerings">{entries.slice(page*6,page*6+6).map(e=>{const done=e.nextLevel===null;return <article className="fate-offering" key={String(e.item.item)}><div className="fate-node"><RealmIcon name={category}/></div><h2>{t(e.item.nameKey)}</h2><p>{t(e.item.descKey)}</p><div className="fate-steps" aria-label={`等級 ${e.currentLevel} / ${e.item.levels.length}`}>{e.item.levels.map((_,i)=><RealmIcon key={i} name="talent" className={i<e.currentLevel?'lit':'unlit'}/>)}</div><footer><span>{!done&&<RealmIcon name="currency"/>}{done?'命軌圓滿':e.nextLevel?.cost}</span><button className="realm-upgrade" aria-label={(done?'已圓滿':e.blockedBy.length?'前置未滿':e.affordable?'提升':'點數不足')+'：'+t(e.item.nameKey)} title={done?'已圓滿':e.blockedBy.length?'前置未滿':e.affordable?'提升':'點數不足'} disabled={done||!e.affordable||e.blockedBy.length>0} onClick={()=>{const r=purchase(e.item.item,meta,defs);if(r.ok){onMeta(r.meta);setNotice(`${t(e.item.nameKey)} · 命星已點亮`);}}}><img src="/art/ui/realms/upgrade-v1.png" alt="" draggable={false}/></button></footer></article>;})}</div></div>{entries.length>6&&<nav className="realm-pages" aria-label="品項分頁"><button aria-label="上一頁" disabled={page===0} onClick={()=>setPage(p=>p-1)}><img src="/art/ui/entry/button-back-v2.png" alt=""/></button><span>{page+1} / {Math.ceil(entries.length/6)}</span><button aria-label="下一頁" disabled={(page+1)*6>=entries.length} onClick={()=>setPage(p=>p+1)}><img src="/art/ui/entry/button-back-v2.png" alt=""/></button></nav>}{notice&&<footer className="realm-footnote" role="status">{notice}</footer>}</section>;
}
