import { ArtControl } from './ArtControl.js';
import { useState } from 'react';
import type { Session, LearningOffer } from '../app/session.js';
import { t } from '../app/bootstrap.js';
import { Hud } from './Hud.js';
export function ScreenLearn({ s, bump, onBack }: { readonly s: Session; readonly bump: () => void; readonly onBack: () => void }): React.ReactElement {
  const [tab, setTab] = useState<'skill' | 'trait'>('skill'); const [showAll, setShowAll] = useState(false); const [notice, setNotice] = useState('');
  const all = s.learningOffers(); const visible = all.filter(x => x.kind === tab && (showAll || x.level > 0 || x.status !== 'locked'));
  const reason = (o: LearningOffer): string => o.status === 'locked' ? `傳授來源：${o.teachers.join('、') || '深關獎勵'}` : o.status === 'attribute' ? `需${t(`attr.${o.attr}.short`)} ${o.need}，目前 ${o.value}` : o.status === 'funds' ? `還差 ${Math.max(0, o.cost - s.learningExp)} 學習點` : o.status === 'battle' ? '本場配置已鎖定，下場戰前可再修習' : o.status === 'max' ? '此生已臻化境' : `需${t(`attr.${o.attr}.short`)} ${o.need} · 已達成`;
  return <><div className="page-heading"><div><span className="eyebrow">修習堂 · 不消耗行動</span><h1>將所學，化為所長</h1></div><ArtControl kind="back" label="返回" onClick={onBack}/></div><p className="page-intro">能力隨歷練自然成長。把學習點留給你想精進的招式與特性。</p><Hud s={s} />
    <div className="learning-toolbar"><div className="segmented"><button className={tab === 'skill' ? 'sel' : ''} onClick={() => { setTab('skill'); }}>技能 <small>{all.filter(x => x.kind === 'skill' && x.level > 0).length}</small></button><button className={tab === 'trait' ? 'sel' : ''} onClick={() => { setTab('trait'); }}>特性 <small>{all.filter(x => x.kind === 'trait' && x.level > 0).length}</small></button></div><label className="toggle-label"><input type="checkbox" checked={showAll} onChange={e => { setShowAll(e.target.checked); }} />顯示尚未學會</label></div>
    <div role="status" className="inline-notice">{notice || (tab === 'skill' ? '已學會的技能可在戰前選三招出陣。' : '特性常駐生效，不占出陣招式格。')}</div>
    {visible.length === 0 ? <div className="empty-state"><span>學</span><h2>此生，尚待名師相授</h2><p>與名士同格共事，有機會學會他擅長的技能與特性。</p><button onClick={() => { setShowAll(true); }}>看看誰能傳授</button></div> : <div className="ability-grid">{visible.map(o => <article key={String(o.id)} className={`ability-card ${o.level === 0 ? 'unlearned' : ''}`}><div className="ability-head"><span className={`ability-mark attr-${o.attr}`}>{t(`attr.${o.attr}.short`)}</span><div><span className="eyebrow">{o.kind === 'skill' ? '出陣技能' : '常駐特性'}</span><h2>{o.name}</h2></div><b className="level-label">{o.level === 0 ? '未習得' : `Lv.${o.level}`}</b></div><div className="level-steps" aria-label={`等級 ${o.level}，最高 ${o.maxLevel}`}>{Array.from({ length: o.maxLevel }, (_, i) => <i key={i} className={i < o.level ? 'filled' : ''} />)}</div><p className="ability-desc">{o.description}</p>{o.level > 0 && <div className="upgrade-preview"><span>效果強度</span><b>×{o.power.toFixed(2)}</b>{o.level < o.maxLevel && <><span>→</span><strong>×{o.nextPower.toFixed(2)}</strong></>}</div>}<p className={`requirement ${o.status === 'ready' ? 'ok' : ''}`}>{reason(o)}</p><button className={o.status === 'ready' ? 'primary' : ''} disabled={o.status !== 'ready'} onClick={() => { const done = s.upgradeAbility(o.id); setNotice(done ? `${o.name}已提升至 Lv.${o.level + 1}，消耗 ${o.cost} 學習點。` : '目前無法升級，請確認能力與學習點。'); bump(); }}>{o.status === 'locked' ? '等待名士傳授' : o.status === 'max' ? '已達最高等級' : `升至 Lv.${o.level + 1}　·　${o.cost} 學習點`}</button></article>)}</div>}</>;
}
