import assert from 'node:assert/strict';
import { createConfiguredBattle,startBattle,tickBattle,castSkill,armyCount,armyComposition,validBattleSnapshot,damageTroop,migrateBattle } from '../../src/app/realtime-battle-model.js';
import { campaignBattle } from '../../src/app/realtime-campaign.js';
import { tacticalImpact,effect } from '../../src/app/battle-tactics.js';
import { Session } from '../../src/app/session.js';
import { begin } from '../../src/modules/campaign.js';
import { defs,newSession,wiring } from './harness.js';
import type {BattleState,Cinematic} from '../../src/contracts/core/realtime-battle.js';
const fixture=(ratio=60,enemyRatio=60)=>{const b=createConfiguredBattle({troops:425,supply:200,supplyMax:200,regen:0,duration:60,skills:[],commanders:[{id:'a',name:'主角',side:'ally',x:125,y:350,homeX:125,pose:'command',poseTime:0,flip:false},{id:'e',name:'敵軍',side:'enemy',x:1470,y:350,homeX:1470,pose:'command',poseTime:0,flip:true}],waveTroops:[600,700],waveNames:['敵軍','敵軍'],allyAttack:1,enemyAttack:1,infantryPercent:ratio,enemyInfantryPercent:enemyRatio});startBattle(b);b.phase='combat';b.units.forEach(u=>u.x=u.homeX);return b;};
const impact=(b:BattleState,mechanic:string)=>{const c:Cinematic={skill:{id:mechanic,name:mechanic,owner:'主角',kind:'charge',key:'1',cost:30,cd:10,damage:90,description:'',mechanic},time:2.5,impacted:false,targetX:1050,targetY:400,damage:0};tacticalImpact(b,c);return c;};
for(const ratio of [0,30,60,100]){const b=fixture(ratio),parts=armyComposition(425,ratio);for(const kind of ['infantry','archer'] as const)assert.equal(b.units.filter(u=>u.side==='ally'&&u.kind===kind).reduce((n,u)=>n+u.hp,0),parts[kind]);assert(b.units.every(u=>u.hp<=50));assert(validBattleSnapshot(b));}
const initial=newSession(123).current,ready=Session.restore(wiring,begin(initial.progress.chapterId,{state:{...initial,progress:{...initial.progress,pendingCampaign:true}},defs},wiring.fx));
for(const ratio of [-1,101,NaN,Infinity,25.5])assert.throws(()=>ready.configureCampaign({skills:[],commanders:[],infantryPercent:ratio}));
ready.configureCampaign({skills:[],commanders:[],infantryPercent:30});assert.equal(campaignBattle(ready.ctx,wiring.fx).infantryPercent,30);assert.throws(()=>ready.configureCampaign({skills:[],commanders:[],infantryPercent:100}));
const noTarget=fixture(60,100),c=impact(noTarget,'cavalry');assert.equal(c.damage,0);noTarget.skills=[c.skill];assert(castSkill(noTarget,c.skill.id));assert.equal(noTarget.supply,170);assert.equal(noTarget.cooldowns[c.skill.id],10);
const converted=fixture(),ids=converted.units.map(u=>u.id),hp=armyCount(converted,'ally');impact(converted,'toarcher');assert.deepEqual(converted.units.map(u=>u.id),ids);assert.equal(armyCount(converted,'ally'),hp);assert(converted.units.some(u=>u.side==='ally'&&u.kind==='archer'&&effect(u,'ready')>0));
const absent=fixture();impact(absent,'lure');const target=absent.units.find(u=>u.absent)!;assert.equal(damageTroop(absent,target,1000),0);assert.equal(armyCount(absent,'enemy'),600);assert.equal(absent.kills,0);
const recruitment=fixture();impact(recruitment,'divide');assert.equal(recruitment.kills,0);assert.equal(recruitment.removed,50);assert.equal(recruitment.waveRemoved?.[1],50);assert.equal(armyCount(recruitment,'enemy'),550);assert.equal(recruitment.units.filter(u=>u.side==='ally'&&!u.temporary).reduce((n,u)=>n+u.hp,0)+recruitment.lost,recruitment.initial);assert(validBattleSnapshot(recruitment));
const reinforcement=fixture();impact(reinforcement,'reinforce');impact(reinforcement,'reinforce');assert.equal(reinforcement.units.filter(u=>u.temporary).reduce((n,u)=>n+u.hp,0),100);for(const u of reinforcement.units.filter(u=>u.temporary))damageTroop(reinforcement,u,100);assert.equal(reinforcement.lost,0);
const snap=fixture();impact(snap,'mounted');assert(snap.arrows.length===3);assert(validBattleSnapshot(snap));const copy=JSON.parse(JSON.stringify(snap)) as BattleState;for(let i=0;i<60;i++){tickBattle(snap,1/60);tickBattle(copy,1/60);}assert.deepEqual(snap,copy,'shots and RNG must resume exactly');
const legacy=fixture() as BattleState;delete (legacy as Partial<BattleState>).arrows;delete (legacy as Partial<BattleState>).rng;for(const u of legacy.units)delete (u as Partial<typeof u>).kind;migrateBattle(legacy);assert(legacy.units.every(u=>u.kind==='infantry'));assert(validBattleSnapshot(legacy));
const archer=fixture(0,100);for(const u of archer.units){u.x=u.side==='ally'?600:950;u.y=400;}for(let i=0;i<100;i++)tickBattle(archer,1/60);assert(archer.arrows.length>0||archer.kills>0,'archers really release damaging arrows');
const melee=fixture(0,100);for(const u of melee.units){u.x=u.side==='ally'?800:850;u.y=400;}for(let i=0;i<15;i++)tickBattle(melee,1/60);assert.equal(melee.arrows.length,0,'engaged archers cannot fire');
for(const d of defs.reader('skill').all().filter(d=>d.battleMechanic)){const b=fixture();assert.doesNotThrow(()=>impact(b,d.battleMechanic!));assert(validBattleSnapshot(b),d.battleMechanic);assert(defs.reader('notable').all().some(n=>n.abilities.skills.some(row=>row.skillId===d.skillId)),d.battleMechanic+' needs a teacher');}
assert.equal(defs.reader('skill').all().filter(d=>d.battleMechanic).length,25);
const backwater=fixture();backwater.traits=[{id:'backwater',owner:'主角',name:'背水',level:1}];for(const u of backwater.units.filter(u=>u.side==='ally'))damageTroop(backwater,u,Math.floor(u.hp*.8));tickBattle(backwater,1/60);assert(backwater.units.some(u=>effect(u,'backwater')>0));assert(backwater.log.some(line=>line.includes('背水')));
console.log('New battle rules passed: ratio/freeze, target whiff, conversion, absence, recruitment, reinforcement, real arrows, save/RNG, 25 taught skills and triggered traits.');
