import assert from 'node:assert/strict';
import {createCardDebate,resolveCardDebate,debateBlock,debateIntent,debateDamage,DEBATE_CARDS,DEFAULT_DEBATE_BUILD,DEBATE_RECOVER,debateHandSize,type DebateCard} from '../../src/app/card-debate-model.js';
import {createEncounterDemo,beginEncounterDemo,tickEncounterDemo,answerContest} from '../../src/app/confrontation-demo.js';
import {armyCount} from '../../src/app/realtime-battle-model.js';
const pair=(x:DebateCard,y:DebateCard,evidence=0)=>{const s=createCardDebate();s.ally.hand[0]=x;s.enemy.hand[0]=y;s.enemyChoice=0;s.ally.evidence=evidence;return s;};
const claim=pair('claim','focus');assert(resolveCardDebate(claim,0));assert.equal(claim.ally.evidence,3);assert(claim.last!.damageToEnemy>0);assert.equal(claim.ally.hand.length,5);
const visual=pair('proof','focus',3),originalHand=[...visual.ally.hand],originalMind=visual.ally.mind,estimate=debateDamage(visual.ally,visual.enemy,'proof');
resolveCardDebate(visual,0);assert.equal(visual.last!.damageToEnemy,estimate,'card estimate matches unopposed damage before evidence is consumed');assert.deepEqual(visual.last!.allyHand,originalHand,'reveal retains the cards used before refilling');assert.equal(visual.last!.allyChange.evidence,-3);assert.equal(visual.last!.enemyChange.heart,-estimate);assert.equal(visual.last!.allyChange.mind,visual.ally.mind-originalMind,'result includes actual capped resource changes');visual.ally.hand[0]='focus';assert.deepEqual(visual.last!.allyHand,originalHand,'reveal snapshot is independent of current hand');
const proof=pair('proof','focus',3);resolveCardDebate(proof,0);const broken=pair('proof','question',3);resolveCardDebate(broken,0);assert(broken.last!.damageToEnemy<proof.last!.damageToEnemy*.4);assert.equal(broken.ally.evidence,0);assert(broken.last!.notes.some(n=>n.includes('失勢')));
const rebut=pair('proof','rebut',3);resolveCardDebate(rebut,0);assert(rebut.last!.damageToAlly>0&&rebut.last!.damageToEnemy<proof.last!.damageToEnemy*.3,'counter blocks and reflects exactly once');
const borrow=pair('borrow','focus');borrow.enemy.momentum=4;resolveCardDebate(borrow,0);assert.equal(borrow.ally.momentum,2);assert.equal(borrow.enemy.momentum,2);
const doubleBorrow=pair('borrow','borrow');resolveCardDebate(doubleBorrow,0);assert.equal(doubleBorrow.ally.momentum,1);assert.equal(doubleBorrow.enemy.momentum,1,'simultaneous borrowing has no resolution-order advantage');
// Hand thresholds use one shared sixteen-card deck; recovery cannot collide with card five.
for(const [int,size] of [[1,3],[39,3],[40,4],[59,4],[60,5],[79,5],[80,6],[100,6]]){
 const v=createCardDebate({...DEFAULT_DEBATE_BUILD,int:int!});assert.equal(debateHandSize(int!),size);assert.equal(v.ally.hand.length,size);assert.equal(v.ally.hand.length+v.ally.deck.length,16);
 const untouched=JSON.stringify(v);assert.equal(resolveCardDebate(v,size!),false);assert.equal(JSON.stringify(v),untouched);
}
const fifth=createCardDebate();fifth.enemy.hand[0]='focus';fifth.enemyChoice=0;assert(resolveCardDebate(fifth,4));assert.equal(fifth.last!.ally,'borrow');assert.equal(fifth.last!.allyFallback,false);
const sixth=createCardDebate({...DEFAULT_DEBATE_BUILD,int:90});sixth.ally.momentum=3;sixth.enemy.hand[0]='rebut';sixth.enemyChoice=0;assert(resolveCardDebate(sixth,5));assert.equal(sixth.last!.ally,'pressure');assert.equal(sixth.last!.damageToAlly,0,'pressure bypasses reflection');
const pressureVs=(card:DebateCard)=>{const v=pair('pressure',card);v.ally.momentum=3;v.enemy.mind=40;resolveCardDebate(v,0);return v;};
const pressureOpen=pressureVs('claim'),pressureRebut=pressureVs('rebut'),pressureFocus=pressureVs('focus'),pressureBorrow=pressureVs('borrow');
assert.equal(pressureOpen.last!.damageToEnemy,pressureRebut.last!.damageToEnemy,'rebut cannot block pressure');assert.equal(pressureFocus.last!.damageToEnemy,Math.round(pressureOpen.last!.damageToEnemy*.5),'focus halves pressure');assert(pressureFocus.enemy.mind>40,'focus still restores mind');assert(pressureBorrow.last!.damageToEnemy<pressureOpen.last!.damageToEnemy*.3,'borrowing removes momentum before burst');assert.equal(pressureOpen.ally.momentum,1,'burst consumes all momentum then gains one from hitting');
const pressureLock=pair('pressure','focus');assert.equal(resolveCardDebate(pressureLock,0),false);assert.match(debateBlock(pressureLock.ally,'pressure'),/聲勢/);
const successfulRebut=pair('rebut','proof');successfulRebut.enemy.evidence=3;resolveCardDebate(successfulRebut,0);assert.equal(successfulRebut.ally.momentum,2,'successful defence enables momentum burst');const baitedRebut=pair('rebut','focus');resolveCardDebate(baitedRebut,0);assert.equal(baitedRebut.ally.momentum,0,'empty defence gives no momentum');
const drain=pair('question','claim');drain.enemy.mind=9;resolveCardDebate(drain,0);assert.equal(drain.enemy.mind,6,'drain after costs cannot make energy negative');assert(drain.enemy.evidence>0,'drain does not retroactively cancel a committed action');
const poor=pair('proof','focus');poor.ally.mind=0;const untouched=JSON.stringify(poor);assert.equal(resolveCardDebate(poor,0),false);assert.equal(JSON.stringify(poor),untouched);assert(resolveCardDebate(poor,DEBATE_RECOVER));assert(poor.ally.mind>0&&poor.ally.hand.length===5);
const intellect=pair('proof','focus',4),weak=pair('proof','focus',4);intellect.ally.build.int=95;weak.ally.build.int=20;resolveCardDebate(intellect,0);resolveCardDebate(weak,0);assert(intellect.last!.damageToEnemy>weak.last!.damageToEnemy);
const high=createCardDebate({...DEFAULT_DEBATE_BUILD,pol:95}),low=createCardDebate({...DEFAULT_DEBATE_BUILD,pol:20});assert(high.ally.maxHeart>low.ally.maxHeart&&high.ally.maxMind>low.ally.maxMind);
const locked=createCardDebate();const choice=locked.enemyChoice,intent=debateIntent(locked);assert.equal(resolveCardDebate(locked,-2),false);assert.equal(locked.enemyChoice,choice);assert.equal(debateIntent(locked),intent);
const unchangedEnemy=locked.enemy.hand[choice];resolveCardDebate(locked,DEBATE_RECOVER);assert.equal(locked.last!.enemy,choice===DEBATE_RECOVER?'focus':unchangedEnemy);
let wins=0,losses=0,draws=0,rounds=0;
for(let seed=0;seed<800;seed++){
 const s=createCardDebate({...DEFAULT_DEBATE_BUILD,trait:(['scholar','orator','counter','calm'] as const)[seed%4]!},undefined,seed);
 while(!s.result){const order:DebateCard[]=s.ally.mind<25?['focus','claim','question','proof','rebut','borrow']:s.enemy.evidence>=2?['question','rebut','proof','claim','borrow','focus']:['proof','claim','question','borrow','rebut','focus'];let index=DEBATE_RECOVER;for(const c of order){const i=s.ally.hand.indexOf(c);if(i>=0&&!debateBlock(s.ally,c)){index=i;break;}}assert(resolveCardDebate(s,index));for(const f of [s.ally,s.enemy]){assert(f.mind>=0&&f.mind<=f.maxMind&&f.heart>=0&&f.heart<=f.maxHeart&&f.evidence<=5&&f.momentum<=4);assert.equal(f.hand.length,5);assert.equal(f.hand.length+f.deck.length+f.discard.length,16);assert(f.hand.every(c=>DEBATE_CARDS[c]));}}
 rounds+=s.history.length;assert(s.history.length<=20);if(s.result==='ally')wins++;else if(s.result==='enemy')losses++;else draws++;assert.equal(resolveCardDebate(s,DEBATE_RECOVER),false);
}
for(const victory of [true,false]){
 const s=createEncounterDemo('cards',123);beginEncounterDemo(s);const until=(fn:()=>boolean)=>{for(let i=0;i<6000&&!fn();i++)tickEncounterDemo(s,1/60);assert(fn());};until(()=>s.contest?.phase==='read');const d=s.contest!.cards!;
 const clock=s.battle.time,supply=s.battle.supply,troops=armyCount(s.battle,'ally');if(victory){d.enemy.heart=1;d.enemy.hand[0]='focus';d.enemyChoice=0;}else{d.ally.heart=1;d.enemy.hand[0]='claim';d.enemyChoice=0;}
 assert(answerContest(s,victory?0:DEBATE_RECOVER));assert.equal(answerContest(s,0),false);until(()=>victory?s.battle.wave===2&&s.battle.phase==='combat':s.battle.status==='finished');assert.equal(s.battle.time,clock);assert.equal(s.battle.supply,supply);assert.equal(armyCount(s.battle,'ally'),victory?troops:0);
}
const paused=createEncounterDemo('cards');beginEncounterDemo(paused);for(let i=0;i<1000&&!paused.contest;i++)tickEncounterDemo(paused,1/60);paused.battle.status='paused';const snap=JSON.stringify(paused);tickEncounterDemo(paused,10);assert.equal(answerContest(paused,DEBATE_RECOVER),false);assert.equal(JSON.stringify(paused),snap);
const draw=pair('focus','focus');draw.round=20;resolveCardDebate(draw,0);assert.equal(draw.result,'draw');
const timed=createEncounterDemo('cards');beginEncounterDemo(timed);for(let i=0;i<2500&&!timed.contest?.cards?.last;i++)tickEncounterDemo(timed,1/60);assert.equal(timed.contest!.cards!.last!.allyFallback,true,'timeout uses the free recovery action');
const sixScene=createEncounterDemo('cards',53);sixScene.debateBuilds={ally:{...DEFAULT_DEBATE_BUILD,int:90},enemy:{...DEFAULT_DEBATE_BUILD}};beginEncounterDemo(sixScene);for(let i=0;i<2000&&sixScene.contest?.phase!=='read';i++)tickEncounterDemo(sixScene,1/60);assert.equal(sixScene.contest?.phase,'read');sixScene.contest!.cards!.ally.momentum=3;assert(answerContest(sixScene,5));assert.equal(sixScene.contest!.cards!.last!.ally,'pressure','the sixth slot survives encounter input validation');assert.equal(sixScene.contest!.cards!.last!.allyFallback,false);assert.equal(answerContest(sixScene,5),false,'reveal blocks double input');
console.log({simulations:800,wins,losses,draws,averageRounds:rounds/800});console.log('Card debate passed: combos, interruption, reflection, stats, locked AI, dead-hand recovery, deck conservation, limits, frozen battle and both retreat outcomes.');
