import type { EventDef } from '../../../src/contracts/core/definitions.js';
import type { Attr, Rarity } from '../../../src/contracts/core/primitives.js';
import {
  dcCurveId,
  eventDefId,
  itemPoolId,
} from '../../../src/contracts/core/ids.js';
import { asKey } from '../../authoring.js';
import { coreDef } from '../pack-id.js';
import { economy } from '../config/economy.js';
export const variedTexts: Record<string, string> = {};
const rows = [
  [
    'lead',
    'pol',
    1,
    '分派新哨',
    '新來的巡哨隊不熟路線，今日只有半個時辰能交班。',
    '帶一班走熟近路',
    '畫出輪班與接應表',
    '僱嚮導帶完所有岔道',
  ],
  [
    'lead',
    'int',
    2,
    '迷途糧車',
    '兩隊糧車在山岔失聯，留下的車轍一深一淺。',
    '守住山口等待回報',
    '循車轍判斷去向',
    '備火把分隊搜索',
  ],
  [
    'lead',
    'pol',
    2,
    '渡口排隊',
    '渡船只能載一隊，傷兵與運糧隊都在等。',
    '依到達次序渡河',
    '按水位調整裝載',
    '租鄰村小舟接送傷兵',
  ],
  [
    'lead',
    'war',
    3,
    '風中軍旗',
    '大風折斷主旗，遠處部隊仍等著進退訊號。',
    '讓近隊依舊令行動',
    '改用號角傳令',
    '派精騎逐隊核實命令',
  ],
  [
    'lead',
    'int',
    4,
    '兩路援軍',
    '兩路友軍都要求你先援，卻說不清敵軍所在。',
    '守住共同退路',
    '對照兩路情報',
    '派斥候備馬連夜核實',
  ],
  [
    'lead',
    'pol',
    5,
    '撤營次序',
    '大軍即將拔營，病帳、工坊與後衛都不能被落下。',
    '先清點可行軍者',
    '編組互援撤離隊',
    '徵調車輛分段接運',
  ],
  [
    'war',
    'lead',
    1,
    '鬆動槍架',
    '新兵訓練時槍架倒下，所幸無人受傷。',
    '扶穩槍架繼續練習',
    '重排兵器與操練間距',
    '買木楔加固全部槍架',
  ],
  [
    'war',
    'int',
    2,
    '夜巡異響',
    '林邊接連響起折枝聲，巡夜的人不敢向前。',
    '守住亮處警戒',
    '分辨聲響與足跡',
    '備燈具組隊細查',
  ],
  [
    'war',
    'lead',
    2,
    '比武爭先',
    '兩名新兵因先後次序吵起來，其他人也跟著起鬨。',
    '分開兩人各練一輪',
    '改成配對協作比試',
    '借護具讓整隊安全輪試',
  ],
  [
    'war',
    'pol',
    3,
    '封存舊刃',
    '一批刃口崩裂的兵器混入待發武庫。',
    '挑出最明顯的壞刃',
    '按損傷分級試驗',
    '請鐵匠逐件整修',
  ],
  [
    'war',
    'int',
    4,
    '狹道護送',
    '運藥隊必須穿過亂石狹道，前方卻沒有可靠探報。',
    '護送到安全岔口',
    '試出可供掩護的站位',
    '僱挑夫分散藥箱運送',
  ],
  [
    'war',
    'lead',
    5,
    '守住缺口',
    '土壘崩出一個缺口，修補隊需要你替他們爭取時間。',
    '用盾陣護住工匠',
    '輪替小隊掩護填土',
    '購木料與繩索架起護障',
  ],
  [
    'int',
    'pol',
    1,
    '錯字軍報',
    '一封軍報把東西兩字塗成一團，送信人已經走遠。',
    '標記疑處等待核實',
    '比對沿途驛站時辰',
    '雇腳程快的人追回信使',
  ],
  [
    'int',
    'lead',
    2,
    '兩張地圖',
    '舊圖有橋，新圖只有渡口；兩張圖都蓋著官印。',
    '採用已知可走的大路',
    '比對河道與季節記錄',
    '購小舟實地勘查',
  ],
  [
    'int',
    'war',
    2,
    '假火辨位',
    '遠山亮起數堆營火，數量多得不合常理。',
    '記下火點繼續觀察',
    '從煙向推算營地位置',
    '備乾糧讓斥候長時間跟查',
  ],
  [
    'int',
    'pol',
    3,
    '封蠟裂痕',
    '密信封蠟有一道新裂痕，內容卻平淡無奇。',
    '如實登記封蠟狀況',
    '比對沿路接手紀錄',
    '另派信使交叉核對',
  ],
  [
    'int',
    'lead',
    4,
    '失約的接應',
    '約好的接應沒有出現，前方也沒留下記號。',
    '退回上個聯絡點',
    '依足跡重建行軍路線',
    '備三路信使分頭尋訪',
  ],
  [
    'int',
    'pol',
    5,
    '糧價疑雲',
    '三處市集同日抬高糧價，軍需官懷疑有人串通。',
    '保存今日報價',
    '交叉核對運量和庫存',
    '雇商旅逐站訪查',
  ],
  [
    'pol',
    'int',
    1,
    '重複的名冊',
    '兩個同名的人領到同一塊田，雙方都帶著見證人。',
    '先登記雙方說法',
    '核對戶籍與田界',
    '請丈量人現場立界',
  ],
  [
    'pol',
    'lead',
    2,
    '修渠分工',
    '上游要堵水修渠，下游農戶卻等著灌田。',
    '先修不影響水路的段落',
    '排出分時供水表',
    '買木板搭臨時引水槽',
  ],
  [
    'pol',
    'int',
    2,
    '糧秤不平',
    '市集兩把秤差了半升，商販與軍需吏各不相讓。',
    '先暫停爭議的交易',
    '用標準砝碼逐一校秤',
    '請匠人校修全場量具',
  ],
  [
    'pol',
    'lead',
    3,
    '失散的戶籍',
    '數戶流民找不到親屬，卻必須先領到過夜的住處。',
    '先登記眼前人數',
    '依故里編組互相尋訪',
    '租空屋暫安置孩童老人',
  ],
  [
    'pol',
    'int',
    4,
    '倉庫漏雨',
    '夜雨打濕角落糧袋，糧官主張全部列作耗損。',
    '隔開受潮糧袋',
    '逐袋檢查分級晾曬',
    '僱人搭棚搶救庫糧',
  ],
  [
    'pol',
    'lead',
    5,
    '軍民共渡',
    '河水上漲，军隊與百姓都要借僅存的橋撤離。',
    '維持單向通行',
    '依行速分批接續',
    '備纜繩加固橋面與護欄',
  ],
] as const;
export const variedCommissions: EventDef[] = rows.map(
  ([attr, sub, rarity, title, body, a, b, c], index) => {
    const id = 'event:work.' + index,
      key = 'event.work.' + index;
    variedTexts[key + '.title'] = title;
    variedTexts[key + '.body'] = body;
    [a, b, c].forEach((v, i) => (variedTexts[key + '.opt.' + i] = v));
    return coreDef('event', id, {
      eventDefId: eventDefId(id),
      trigger: {
        kind: 'commission',
        attr: attr as Attr,
        rarity: rarity as Rarity,
      },
      mechanic: 'investment',
      unique: false,
      collectible: false,
      weight: 100,
      titleKey: asKey(key + '.title'),
      bodyKey: asKey(key + '.body'),
      paramSlots: [],
      requirements: [],
      options: (['low', 'mid', 'high'] as const).map((tier, i) => ({
        tier,
        labelKey: asKey(key + '.opt.' + i),
        requirements: [],
        check:
          i === 1
            ? { attr: sub as Attr, dcCurveId: dcCurveId('dc:normal') }
            : null,
        moneyCost: i === 2 ? economy.investmentCosts[rarity - 1]! : 0,
        practice: [{ attr: (i === 1 ? sub : attr) as Attr, weight: 1 }],
        rewards: [
          {
            kind: 'merit',
            merit: attr === 'lead' || attr === 'war' ? 'martial' : 'civil',
            amount: i + 1,
          },
          ...(i === 2
            ? [
                {
                  kind: 'itemPool' as const,
                  poolId: itemPoolId('pool:item.low'),
                  chance: 0.2,
                },
              ]
            : []),
        ],
      })),
    });
  },
);
