export type UnitKind = 'infantry' | 'archer';
export interface Arrow { id:number; side:Side; targetId:number; x:number;y:number;fromX:number;fromY:number;toX:number;toY:number;elapsed:number;duration:number;damage:number;hit:boolean;friendly:boolean;owner?:string;sourceId?:number;retarget?:boolean }
export type Side = 'ally' | 'enemy';
export type SkillKind = 'fire' | 'charge' | 'mounted' | 'pincer' | 'inspire';
export interface DemoSkill { id:string; name:string; owner:string; key:string; kind:SkillKind; cost:number; cd:number; damage:number; description:string; effect?:'damage'|'heal'|'buff'|'debuff'; power?:number; effectDuration?:number; support?:boolean;mechanic?:string;level?:number }
export interface Troop {armyId?:string;facingLeft?:boolean;kind:UnitKind;temporary?:boolean;absent?:number;effects?:Record<string,number>;id:number;side:Side;hp:number;maxHp:number;x:number;y:number;homeX:number;lane:number;attack:number;targetId:number;struck:boolean;pose:'guard'|'run'|'slash'|'hit'|'dead';poseTime:number;deathTime:number;hitTime:number;seed:number}
export type WavePhase='entry'|'reveal'|'start'|'combat'|'fallen'|'flee'|'cheer'|'exit'|'fade-out'|'fade-in';
export interface Commander {id:string;name:string;side:Side;x:number;y:number;homeX:number;pose:'command'|'cheer'|'move';poseTime:number;flip:boolean; portrait?:string}
export interface Cinematic {hitIds?:number[];skill:DemoSkill;time:number;impacted:boolean;targetX:number;targetY:number;damage:number}
export interface BattleTrait {id:string;owner:string;name:string;level:number}
export interface BattleState {followupSkill?:DemoSkill|null;maxWaves?:number;traits?:BattleTrait[];traitMarks?:Record<string,number>;terrain?:'plain'|'water'|'mountain';removed?:number;waveKills?:Record<number,number>;waveRemoved?:Record<number,number>;infantryPercent:number;enemyInfantryPercent:number;arrows:Arrow[];rng:number;skills:readonly DemoSkill[];groupSize:number;supplyMax:number;regen:number;allyAttack:number;enemyAttack:number;buffPower:number;debuff:number;debuffPower:number;waveTroops:readonly number[];waveNames:readonly string[];units:Troop[];commanders:Commander[];phase:WavePhase;phaseTime:number;defeated:Side|null;enemyInitial:number;time:number;duration:number;supply:number;kills:number;lost:number;initial:number;nextId:number;wave:number;cooldowns:Record<string,number>;buff:number;cinematic:Cinematic|null;status:'ready'|'running'|'paused'|'finished';reason:string;castCount:number;traitUntil:number;traitReady:boolean;log:string[]}
