import type { EventDef } from '../../src/contracts/core/definitions.js';
import type { Attr } from '../../src/contracts/core/primitives.js';
import {
  eventDefId,
  eventChainId,
  notableId,
} from '../../src/contracts/core/ids.js';
import { asKey } from '../authoring.js';
import { weiDef } from './pack-id.js';
export const earlyTexts: Record<string, string> = {};
export const earlyStories: EventDef[] = [];
const rows = [
  [
    'caocao',
    '曹操',
    'lead',
    'int',
    '帳外借火',
    '曹操蹲在熄了的灶旁，拿折斷的箭桿撥灰。他問你：先替自己煮粥，還是先替巡夜的人燒水？',
    '先把巡夜的熱水送去',
    '分出兩個灶，同時開火',
    '他接過空水壺，把下一班巡哨交給了你。',
    '他看著並起的兩縷炊煙，笑說你倒會分派人手。',
    '雨夜改令',
    '前日的巡哨遇雨誤時。曹操將原令攤開，讓你補一條新規矩。',
    '改成兩班互相接應',
    '保留班次，備一條雨天路線',
  ],
  [
    'zhangliao',
    '張遼',
    'lead',
    'war',
    '城門問路',
    '張遼剛到營地，攤開一張缺了東門的草圖。他請你指出最容易走散的地方。',
    '帶他重走一遍門道',
    '站上高處補齊草圖',
    '走到岔路時，他特意等你說完才下判斷。',
    '他在你指出的缺口旁添了一面旗。',
    '兩面旗',
    '張遼照著你們補的圖試走，新兵卻分不清兩面相近的旗。',
    '陪新兵反覆辨旗',
    '把口令和旗色配成一組',
  ],
  [
    'yujin',
    '于禁',
    'lead',
    'pol',
    '一根營繩',
    '于禁重量營門的繩距，一個新兵怯怯說尺有缺口。他把尺遞給你。',
    '重新量過每段繩距',
    '先讓新兵示範他的量法',
    '他收起錯尺，當眾更正了自己寫下的數字。',
    '新兵終於抬起頭，于禁記住了他的名字。',
    '遲到的點名',
    '點名冊少了一人，原來是送病友去醫帳。于禁要你補上處置。',
    '補足值勤，再註明緣由',
    '先排替班，再核實病情',
  ],
  [
    'xiahoudun',
    '夏侯惇',
    'war',
    'pol',
    '井邊抬桶',
    '夏侯惇扛著漏水的木桶，堅持要先讓傷兵喝上水。井邊只剩你和一堆麻繩。',
    '扛另一桶與他輪流送',
    '用麻繩和木片補住漏口',
    '他抹了把汗，說下回換他替你分擔。',
    '水終於不再漏，他把剩下的麻繩收得整齊。',
    '缺口的飯碗',
    '傷兵把補好的桶送回，還附了一隻缺口飯碗。夏侯惇問你該怎麼回禮。',
    '替他們補齊值夜人手',
    '帶工匠修好整排餐具',
  ],
  [
    'dianwei',
    '典韋',
    'war',
    'lead',
    '分餅',
    '典韋面前的餅堆很快見底。他看見你還沒領飯，悄悄把最後一塊推過來。',
    '掰開餅，一人一半',
    '幫他值一班，讓他再領飯',
    '他接過半塊餅，往旁邊挪出一個座位。',
    '他回來時帶了兩份飯，說欠人的班得記清。',
    '門外的貓',
    '夜守時一隻貓翻倒食盆。典韋沒有追，卻擔心營門的聲響被掩蓋。',
    '挪食盆，留出安靜哨位',
    '陪他重辨幾種夜間腳步',
  ],
  [
    'lejin',
    '樂進',
    'war',
    'lead',
    '短梯',
    '樂進試著把比旁人短一截的梯子架穩。他說只要第一步踩牢，後面就好辦。',
    '替他穩梯，輪流試登',
    '找木料補出一級踏板',
    '他下梯後又扶住梯腳，等你也試一次。',
    '他踩了踩新踏板，讓你在名冊上寫上兩人的名字。',
    '先登之後',
    '練習結束，新兵只記得第一個登頂的人。樂進讓你替扶梯的人說句話。',
    '逐個補上扶梯者的姓名',
    '安排下一次互換位置',
  ],
  [
    'guojia',
    '郭嘉',
    'int',
    'pol',
    '半盤棋',
    '郭嘉留著半盤殘棋去倒茶，回來發現風把棋子吹亂了。他問你還記得幾手。',
    '照記憶復原棋局',
    '從散子重新找一條路',
    '他沒有計較錯位的棋子，只問你為何記住那一步。',
    '他把原來的勝負擱下，陪你走完新局。',
    '欠下的茶',
    '郭嘉說上回那局棋欠你一盞茶，卻只拿出兩份互相矛盾的軍報。',
    '追問兩名信使走過的路',
    '先找兩份報告共同的細節',
  ],
  [
    'jiaxu',
    '賈詡',
    'int',
    'war',
    '沉默的座位',
    '帳中眾人爭論不休，賈詡只挪出半張席。他示意你先坐，聽完再說。',
    '記下每人沒有回答的問題',
    '盯住他們共用的那張地圖',
    '散帳後，他指著你的空白處說：這才是明日要問的。',
    '他把地圖折到一道河口，留給你繼續看。',
    '留白的回信',
    '賈詡收到一封催答的信，把最後一句留空。你要替他填的是期限，還是條件？',
    '寫明必須核實的條件',
    '訂下下一次回覆的日期',
  ],
  [
    'chengyu',
    '程昱',
    'int',
    'pol',
    '袋底餘糧',
    '程昱把糧袋倒過來，袋底還落下半碗米。他問你這應算耗損還是庫存。',
    '逐袋清點，重寫帳數',
    '先修袋口，再訂耗損準則',
    '他把半碗米歸入公帳，讓你留下驗算的記號。',
    '他拍了拍新袋口，說規矩得能裝住米才算數。',
    '兩份領糧單',
    '相鄰兩隊拿著相同的領糧單來催糧。程昱要你查出重複處。',
    '沿簽名追查先後',
    '核對實到人數再分糧',
  ],
  [
    'xunyu',
    '荀彧',
    'pol',
    'int',
    '借來的燈',
    '荀彧見你借燈抄名冊，便將自己的燈移到桌中央。他問哪一欄最難填。',
    '請教如何記錄流民來處',
    '先替他整理散落的書簡',
    '他把幾個容易混淆的地名一一寫在旁邊。',
    '桌面空出一角，他邀你一起核對最後一頁。',
    '名冊上的空格',
    '那份名冊多了一戶找不到故里的孩子。荀彧讓你決定先補什麼。',
    '先找願意照看的鄰戶',
    '先尋親，再補登居所',
  ],
  [
    'chenqun',
    '陳群',
    'pol',
    'int',
    '錯了一筆',
    '陳群發現文書上的一筆讓兩個人領到同一職。他請你說明先通知誰。',
    '先通知兩人，說明錯處',
    '先核原稿，保留更正記錄',
    '兩人都留下來等重核，他鬆開了緊握的筆。',
    '他在更正處署名，沒有把責任推給抄手。',
    '無名的推薦',
    '一份沒有署名的薦書寫得十分懇切。陳群問你該用什麼驗證它。',
    '安排當面試做一件事',
    '找曾共事的人交叉詢問',
  ],
  [
    'maojie',
    '毛玠',
    'pol',
    'lead',
    '舊袍',
    '毛玠縫著磨破的袍袖，旁邊是剛送來的布匹。他說先看看營裡誰更需要。',
    '帶他走訪最遠的哨棚',
    '把缺衣人數列成清單',
    '回來時他的袍袖仍破著，清單上卻多了幾個名字。',
    '他把布匹逐卷對好，留下你可追查的記號。',
    '送回的布',
    '有人把領到的布送回，說家中尚有餘。毛玠讓你決定如何處理。',
    '轉交漏登的傷兵',
    '記下歸還，重查分配數量',
  ],
];
for (const row of rows) {
  const [id, name, primary, secondary, t1, b1, a1, c1, r1, r2, t2, b2, a2, c2] =
    row as string[];
  for (const step of [0, 1] as const) {
    const slug = id + (step === 0 ? '-meeting' : '-familiar'),
      key = 'event.wei.' + slug;
    const title = step === 0 ? t1! : t2!,
      body = step === 0 ? b1! : b2!;
    earlyTexts[key + '.title'] = title;
    earlyTexts[key + '.body'] = body;
    earlyTexts[key + '.a'] = step === 0 ? a1! : a2!;
    earlyTexts[key + '.b'] = step === 0 ? c1! : c2!;
    earlyTexts[key + '.result.a'] =
      step === 0
        ? r1!
        : name + '把你的做法記入當日紀錄，約好下次一起核對結果。';
    earlyTexts[key + '.result.b'] =
      step === 0 ? r2! : name + '留下另一份草稿，請你下次共事時再談其中得失。';
    earlyStories.push(
      weiDef('event', 'event:wei.' + slug, {
        eventDefId: eventDefId('event:wei.' + slug),
        trigger: {
          kind: 'notable',
          chainId: eventChainId('chain:early.' + id),
          step,
          cast: [
            {
              notableId: notableId('notable:' + id),
              minStage: step === 0 ? 'stranger' : 'acquainted',
            },
          ],
        },
        progression: {
          rarity: step === 0 ? 1 : 2,
          previous:
            step === 0 ? [] : [eventDefId('event:wei.' + id + '-meeting')],
        },
        mechanic: 'relationship',
        unique: true,
        collectible: true,
        weight: 100,
        titleKey: asKey(key + '.title'),
        bodyKey: asKey(key + '.body'),
        paramSlots: [],
        requirements: [],
        options: ['a', 'b'].map((side, i) => ({
          tier: 'story',
          labelKey: asKey(key + '.' + side),
          resultKey: asKey(key + '.result.' + side),
          requirements: [],
          check: null,
          practice: [
            { attr: (i === 0 ? primary : secondary) as Attr, weight: 1 },
          ],
          rewards: [
            {
              kind: 'merit',
              merit:
                primary === 'lead' || primary === 'war' ? 'martial' : 'civil',
              amount: 1,
            },
          ],
        })),
      }),
    );
  }
}
